<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model;

/**
 * Class ApiServiceInterface
 */
interface ApiServiceInterface
{
    /**
     * @return \Frenet\Command\PostcodeInterface
     */
    public function postcode();

    /**
     * @return \Frenet\Command\TrackingInterface
     */
    public function tracking();

    /**
     * @return \Frenet\Command\ShippingInterface
     */
    public function shipping();
}
