<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model;

/**
 * Class ServiceFinderInterface
 */
interface ServiceFinderInterface
{
    /**
     * @param $trackingNumber
     * @return \Frenet\ObjectType\Entity\Shipping\Info\ServiceInterface|null
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function findByTrackingNumber($trackingNumber);
}
