<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Quote;

use Magento\Catalog\Model\Product;
use Magento\Quote\Model\Quote\Item\AbstractItem;

/**
 * Class ItemValidator
 */
class ItemValidator implements QuoteItemValidatorInterface
{
    /**
     * @inheritDoc
     */
    public function validate(AbstractItem $item)
    {
        if ($this->getProduct($item)->isComposite()) {
            return false;
        }

        if ($this->getProduct($item)->isVirtual()) {
            return false;
        }

        return true;
    }

    /**
     * @param AbstractItem $item
     *
     * @return bool|Product
     */
    private function getProduct(AbstractItem $item)
    {
        /** @var Product $product */
        $product = $item->getProduct();
        return $product;
    }
}
