<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Quote;

use MagedIn\Frenet\Model\Quote\Calculators\PriceCalculatorFactory;
use Magento\Quote\Model\Quote\Item\AbstractItem as QuoteItem;

/**
 * Class ItemPriceCalculator
 * @SuppressWarnings(PHPMD.LongVariable)
 */
class ItemPriceCalculator
{
    /**
     * @var PriceCalculatorFactory
     */
    private $priceCalculatorFactory;

    public function __construct(
        PriceCalculatorFactory $priceCalculatorFactory
    ) {
        $this->priceCalculatorFactory = $priceCalculatorFactory;
    }

    /**
     * @param QuoteItem $item
     *
     * @return float
     */
    public function getPrice(QuoteItem $item)
    {
        return $this->priceCalculatorFactory->create($item)->getPrice($item);
    }

    /**
     * @param QuoteItem $item
     *
     * @return float
     */
    public function getFinalPrice(QuoteItem $item)
    {
        return $this->priceCalculatorFactory->create($item)->getFinalPrice($item);
    }
}
