<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Quote;

use MagedIn\Frenet\Model\Config;
use MagedIn\Frenet\Model\Packages\PackageLimit;
use MagedIn\Frenet\Service\RateRequestProvider;
use Magento\Quote\Model\Quote\Address\RateRequest;

/**
 * Class MultiQuoteValidator
 */
class MultiQuoteValidator implements MultiQuoteValidatorInterface
{
    /**
     * @var Config
     */
    private $config;

    /**
     * @var PackageLimit
     */
    private $packageLimit;

    /**
     * @var RateRequestProvider
     */
    private $rateRequestProvider;

    public function __construct(
        Config $config,
        PackageLimit $packageLimit,
        RateRequestProvider $rateRequestProvider
    ) {
        $this->config = $config;
        $this->packageLimit = $packageLimit;
        $this->rateRequestProvider = $rateRequestProvider;
    }

    /**
     * @inheritDoc
     */
    public function canProcessMultiQuote(): bool
    {
        /** @var RateRequest $rateRequest */
        $rateRequest = $this->rateRequestProvider->getRateRequest();

        if (!$this->config->isMultiQuoteEnabled()) {
            return false;
        }

        $isUnlimited = $this->packageLimit->isUnlimited();
        $isOverweight = $this->packageLimit->isOverWeight((float) $rateRequest->getPackageWeight());

        if (!$isUnlimited && !$isOverweight) {
            return false;
        }

        /** @var \Magento\Quote\Model\Quote\Item\AbstractItem $item */
        foreach ($rateRequest->getAllItems() as $item) {
            /**
             * If any single product is overweight then the multi quote cannot be done.
             */
            if ($this->packageLimit->isOverWeight((float) $item->getWeight())) {
                return false;
            }
        }
        return true;
    }
}
