<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Quote;

use Magento\Quote\Model\Quote\Item\AbstractItem;

/**
 * Class QuoteItemValidatorInterface
 */
interface QuoteItemValidatorInterface
{
    /**
     * @param AbstractItem $item
     *
     * @return boolean
     */
    public function validate(AbstractItem $item);
}
