/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
define([
    'uiComponent',
    'Magento_Checkout/js/model/shipping-rates-validator',
    'Magento_Checkout/js/model/shipping-rates-validation-rules',
    'frenetShippingRatesValidator',
    'frenetShippingRatesValidationRules'
], function (
    Component,
    defaultShippingRatesValidator,
    defaultShippingRatesValidationRules,
    ratesValidator,
    ratesValidationRules
) {
    'use strict';

    defaultShippingRatesValidator.registerValidator('magedin_frenet', ratesValidator);
    defaultShippingRatesValidationRules.registerRules('magedin_frenet', ratesValidationRules);

    return Component;
});
