<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\Model\Catalog\Product\View\RateRequestBuilder;

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Framework\DataObject;

interface BuilderInterface
{
    /**
     * @param ProductInterface $product
     * @param DataObject       $request
     * @param array            $options
     *
     * @return void
     */
    public function build(ProductInterface $product, DataObject $request, array $options = []);
}
