/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

var config = {
    map: {
        '*': {
            frenetProductViewQuote: 'MagedIn_Frenet/js/catalog/product/view/quote'
        }
    }
};
