<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\ViewModel\Catalog\Product\View;

use MagedIn\Frenet\Block\Catalog\Product\View\Quote as QuoteBlock;
use MagedIn\Frenet\Model\Config;

/**
 * Class Quote
 *
 * @package MagedIn\Frenet\ViewModel\Catalog\Product\View
 */
class Quote implements \Magento\Framework\View\Element\Block\ArgumentInterface
{
    /**
     * @var string
     */
    const URI_PATH = 'frenet/product/quote';

    /**
     * @var QuoteBlock
     */
    private $block;

    /**
     * @var Config
     */
    private $config;

    public function __construct(
        Config $config
    ) {
        $this->config = $config;
    }

    public function setBlock(QuoteBlock $block)
    {
        $this->block = $block;
        return $this;
    }

    /**
     * @return bool
     */
    public function isProductQuoteAllowed() : bool
    {
        if (!$this->block->getProduct()) {
            return false;
        }

        if (!$this->config->isProductQuoteEnabled()) {
            return false;
        }

        $typeId = $this->block->getProduct()->getTypeId();
        return $this->config->isProductQuoteAllowed($typeId);
    }

    /**
     * @return string
     */
    public function getUrl() : string
    {
        return $this->getBaseUrl() . self::URI_PATH;
    }

    /**
     * @return string
     */
    private function getBaseUrl() : string
    {
        return $this->block->getBaseUrl();
    }
}
