<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\Model\Catalog\Product\View;

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Quote\Model\Quote\Item\AbstractItem as QuoteItem;

class QuoteItemConvertor
{
    /**
     * @var \Magento\Quote\Model\Quote\ItemFactory
     */
    private $itemFactory;

    public function __construct(
        \Magento\Quote\Model\Quote\ItemFactory $itemFactory
    ) {
        $this->itemFactory = $itemFactory;
    }

    /**
     * @param ProductInterface $product
     * @param int              $qty
     *
     * @return QuoteItem
     */
    public function convert(ProductInterface $product, int $qty = 1) : QuoteItem
    {
        return $this->createCartItem($product, $qty);
    }

    /**
     * @param ProductInterface $product
     * @param int              $qty
     *
     * @return QuoteItem
     */
    private function createCartItem(ProductInterface $product, int $qty) : QuoteItem
    {
        $item = $this->itemFactory->create();

        $item->setProduct($product);
        $item->setId($product->getId());
        $item->setStoreId($product->getStoreId());
        $item->setQty($qty);
        $item->setQtyToAdd($qty);
        $item->setPrice($product->getFinalPrice($qty));
        $item->setRowTotal($item->getPrice() * $qty);

        return $item;
    }
}
