<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Catalog\Product\View;

use Magento\Catalog\Api\Data\ProductInterface;

/**
 * Class QuoteInterface
 */
interface QuoteInterface
{
    /**
     * @param ProductInterface $product
     *
     * @return array
     */
    public function quote(ProductInterface $product) : array;

    /**
     * @param int $productId
     *
     * @return array
     */
    public function quoteByProductId(int $productId) : array;

    /**
     * @param string $productSku
     *
     * @return array
     */
    public function quoteByProductSku(string $productSku) : array;
}
