<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\Service;

use Magento\Framework\Exception\LocalizedException;
use Magento\Quote\Model\Quote\Address\RateRequest;
use Magento\Quote\Model\Quote\Address\RateRequestFactory;

/**
 * Class RateRequestProvider
 *
 * @package MagedIn\Frenet\Service
 */
class RateRequestProvider
{
    /**
     * @var RateRequest
     */
    private $rateRequest;

    /**
     * @var RateRequestFactory
     */
    private $rateRequestFactory;

    public function __construct(
        RateRequestFactory $rateRequestFactory
    ) {
        $this->rateRequestFactory = $rateRequestFactory;
    }

    /**
     * @return RateRequest
     */
    public function createRateRequest()
    {
        return $this->rateRequestFactory->create();
    }

    /**
     * @param RateRequest $rateRequest
     *
     * @return $this
     */
    public function setRateRequest(RateRequest $rateRequest): self
    {
        $this->rateRequest = $rateRequest;
        return $this;
    }

    /**
     * @return RateRequest
     * @throws LocalizedException
     */
    public function getRateRequest(): RateRequest
    {
        if ($this->rateRequest) {
            return $this->rateRequest;
        }

        throw new LocalizedException(__('Rate Request is not set.'));
    }

    /**
     * @return $this
     */
    public function clear(): self
    {
        $this->rateRequest = null;
        return $this;
    }
}
