<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Frenet\Model\Validator;

/**
 * Class PostcodeValidator
 */
class PostcodeValidator
{
    /**
     * @var \MagedIn\Frenet\Model\Formatters\PostcodeNormalizer
     */
    private $postcodeNormalizer;

    public function __construct(
        \MagedIn\Frenet\Model\Formatters\PostcodeNormalizer $postcodeNormalizer
    ) {
        $this->postcodeNormalizer = $postcodeNormalizer;
    }

    /**
     * @param string|null $postcode
     *
     * @return bool
     */
    public function validate(string $postcode = null): bool
    {
        if (empty($postcode)) {
            return false;
        }

        if (!((int) $this->postcodeNormalizer->format($postcode))) {
            return false;
        }

        return true;
    }
}
