<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\Controller\Product;

use MagedIn\Frenet\Api\QuoteProductInterface;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\Action\HttpPostActionInterface;
use Magento\Framework\Controller\ResultFactory;

/**
 * Class Quote
 *
 * @package MagedIn\Frenet\Controller\Catalog\Product
 */
class Quote extends Action implements HttpPostActionInterface
{
    /**
     * @var QuoteProductInterface
     */
    private $quoteProduct;

    /**
     * @param Context $context
     * @param QuoteProductInterface $quoteProduct
     */
    public function __construct(
        Context $context,
        QuoteProductInterface $quoteProduct
    ) {
        parent::__construct($context);
        $this->quoteProduct = $quoteProduct;
    }

    /**
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $productId = (int) $this->getRequest()->getParam('product');
        $postcode = (string) $this->getRequest()->getParam('postcode');
        $qty = (float) $this->getRequest()->getParam('qty');
        $options = (array) $this->getRequest()->getParams();

        try {
            /** @var \Magento\Framework\Controller\Result\Json $result */
            $page = $this->resultFactory->create(ResultFactory::TYPE_JSON);
            $rates = $this->quoteProduct->quoteByProductId($productId, $postcode, $qty, $options);

            $page->setData([
                'error' => false,
                'rates' => $rates,
            ]);
        } catch (\Exception $exception) {
            $page->setData([
                'error' => true,
                'message' => $exception->getMessage(),
            ]);
        }

        return $page;
    }
}
