<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Quote\Calculators;

use MagedIn\Frenet\Model\Quote\ItemQuantityCalculatorInterface;
use Magento\Quote\Model\Quote\Item\AbstractItem as QuoteItem;

/**
 * Class DefaultPriceCalculator
 * @SuppressWarnings(PHPMD.LongVariable)
 */
class DefaultPriceCalculator implements PriceCalculatorInterface
{
    /**
     * @var ItemQuantityCalculatorInterface
     */
    private $itemQtyCalculator;

    public function __construct(
        ItemQuantityCalculatorInterface $itemQuantityCalculator
    ) {
        $this->itemQtyCalculator = $itemQuantityCalculator;
    }

    /**
     * @inheritDoc
     */
    public function getPrice(QuoteItem $item): float
    {
        return $item->getPrice();
    }

    /**
     * @inheritDoc
     */
    public function getFinalPrice(QuoteItem $item): float
    {
        if (!$item->getRowTotal()) {
            $item->calcRowTotal();
        }

        /**
         * If the item price is still not calculated then fallback to product final price.
         */
        if (!$item->getRowTotal()) {
            $basePrice = $item->getProduct()->getFinalPrice($item->getQty());
            $item->setRowTotal($basePrice * $item->getQty());
        }

        return $item->getRowTotal() / $this->itemQtyCalculator->calculate($item);
    }
}
