<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Cache\CacheKeyGenerator;

use MagedIn\Frenet\Model\Config;
use MagedIn\Frenet\Model\Cache\CacheKeyGeneratorInterface;
use MagedIn\Frenet\Model\Formatters\PostcodeNormalizer;
use MagedIn\Frenet\Service\RateRequestProvider;
use Magento\Framework\Exception\LocalizedException;

class PostcodeGenerator implements CacheKeyGeneratorInterface
{
    /**
     * @var RateRequestProvider
     */
    private RateRequestProvider $requestProvider;

    /**
     * @var Config
     */
    private Config $config;

    /**
     * @var PostcodeNormalizer
     */
    private PostcodeNormalizer $postcodeNormalizer;

    /**
     * @param PostcodeNormalizer $postcodeNormalizer
     * @param RateRequestProvider $requestProvider
     * @param Config $config
     */
    public function __construct(
        PostcodeNormalizer $postcodeNormalizer,
        RateRequestProvider $requestProvider,
        Config $config
    ) {
        $this->requestProvider = $requestProvider;
        $this->config = $config;
        $this->postcodeNormalizer = $postcodeNormalizer;
    }

    /**
     * @inheritDoc
     * @throws LocalizedException
     */
    public function generate(): string
    {
        $destPostcode = $this->requestProvider->getRateRequest()->getDestPostcode();
        $origPostcode = $this->config->getOriginPostcode();

        return $this->postcodeNormalizer->format($destPostcode) . '-' .
            $this->postcodeNormalizer->format($origPostcode);
    }
}
