<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types = 1);

namespace MagedIn\Frenet\Model\Formatters;

/**
 * Class PostcodeNormalizer
 */
class PostcodeNormalizer
{
    /**
     * @param string $postcode
     *
     * @return string
     */
    public function format(string $postcode = null)
    {
        $postcode = preg_replace('/[^0-9]/', "", "".$postcode);
        $postcode = str_pad($postcode, 8, '0', STR_PAD_LEFT);

        return $postcode;
    }
}
