<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Frenet\Api;

use MagedIn\Frenet\Api\Data\ProductQuoteOptionsInterface;

interface QuoteProductInterface
{
    /**
     * @param int    $id
     * @param string $postcode
     * @param int    $qty
     * @param array  $options
     *
     * @return array
     */
    public function quoteByProductId(int $id, string $postcode, int $qty = 1, array $options = []) : array;

    /**
     * @param string $sku
     * @param string $postcode
     * @param int    $qty
     * @param array  $options
     *
     * @return array
     */
    public function quoteByProductSku(string $sku, string $postcode, int $qty = 1, array $options = []) : array;
}
