<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types = 1);

namespace MagedIn\Frenet\Test\Unit\Model;

use MagedIn\Frenet\Model\ModuleMetadata;
use MagedIn\Frenet\Test\Unit\TestCase;
use Magento\Framework\Composer\ComposerInformation;
use PHPUnit\Framework\MockObject\MockObject;

/**
 * Class ModuleMetadata
 */
class ModuleMetadataTest extends TestCase
{
    /**
     * @var string
     */
    private $version = '2.1.4';

    /**
     * @var ModuleMetadata
     */
    private $productMetadata;

    /**
     * @var ComposerInformation | MockObject
     */
    private $composerInformation;

    protected function setUp(): void
    {
        $this->composerInformation = $this->createMock(ComposerInformation::class);
        $this->productMetadata = $this->getObject(ModuleMetadata::class, [
            'composerInformation' => $this->composerInformation
        ]);
    }

    /**
     * @test
     */
    public function getPackageVersion()
    {
        $this->prepareComposerInformation();
        $expectedVersion = '2.1.4 (Installed Via Composer)';
        $this->assertEquals($expectedVersion, $this->productMetadata->getVersion());
    }

    /**
     * @test
     */
    public function getPackageUnknownVersion()
    {
        $this->assertEquals('Unknown Module Version', $this->productMetadata->getVersion());
    }

    /**
     * @test
     */
    public function getPackageName()
    {
        $this->prepareComposerInformation();
        $this->assertEquals(ModuleMetadata::PACKAGE_NAME, $this->productMetadata->getName());
    }

    /**
     * @test
     */
    public function getPackageType()
    {
        $this->prepareComposerInformation();
        $this->assertEquals(ModuleMetadata::PACKAGE_TYPE, $this->productMetadata->getType());
    }

    private function prepareComposerInformation()
    {
        $this->composerInformation->method('getInstalledMagentoPackages')->willReturn($this->getPackageInformation());
    }

    /**
     * @return array
     */
    private function getPackageInformation()
    {
        $packageInformation = [
            ModuleMetadata::PACKAGE_NAME => [
                'name' => ModuleMetadata::PACKAGE_NAME,
                'type' => ModuleMetadata::PACKAGE_TYPE,
                'version' => $this->version
            ]
        ];

        return $packageInformation;
    }
}
